### ISSUE TITLE
Shitty design decisions by spotify

### ISSUE THREAD

**Issue by zachpmanson** [zachpmanson/notes#106]
smart shuffle button cycle causing a blocking loading icon before you can turn it of on android app

the smart shuffle panel pop up

the smart shuffle button cycle desyncing on rapid presses in desktop app

**Comment by pavo-etc** [comment]
On Android you can swipe the player interface down like pocket casts, but you cannot swipe it back up.  Usually swiping up triggers a song skip

**Comment by pavo-etc** [comment]
(android) Can swipe a song right from within a playlist to add it to the queue but this doesn't work if the playlist is a blend

**Comment by pavo-etc** [comment]
not exactly shitty but... questionable results

https://engineering.atspotify.com/2014/02/how-to-shuffle-songs/

**Comment by pavo-etc** [comment]
https://community.spotify.com/t5/Live-Ideas/All-Platforms-Option-to-have-a-true-shuffle/idc-p/5720067#M274807

**Comment by zachpmanson** [comment]
Custom order is not an sorting option when adding a song to playlist on mobile![Screenshot_20240130-173904.png](https://github.com/zachpmanson/notes/assets/24368336/f411e691-c80c-4295-a7f7-8b7dda2c44e8)
