### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by zachpmanson** [zachpmanson/notes#66]
https://toot.cafe/@cagrimmett/111253782501849619

Will need to think about how this is implemented

**Comment by pavo-etc** [comment]
https://elk.zone/toot.cafe/@cagrimmett/111254234681120813

Send chuck a link when its done

**Comment by zachpmanson** [comment]
Could have RSS feeds based on tags, so someone would be able to subscribe to any particular topic.  Then could just have "#blog" and use that as the blog.  That would allow arbitrary pages to go into the blog but not changing their location in the wiki.  It would also mean I could have an incomplete page, and only add the "#blog" tag when I'm am ready to "publish" it.

**Comment by zachpmanson** [comment]
If feed posts are done via tags, then will need some way to track date of publish etc for rss meta.  Could tie into #162

**Comment by zachpmanson** [comment]
Promising
WIDTH=35        # Column padding width
DIR=.           # You can substitute this for a directory name
for filename in "${DIR}"/*
do 
  created_date="$(git log -1 --format='%ai' --reverse $filename)"
  printf "%-${WIDTH}s |      %s \n" "$created_date" $filename
done | sort

**Comment by zachpmanson** [comment]
Could add ochrs function that takes a tagname as an arg and makes a blog style interface for files within it, ordered chronologically?  This would be a kind of index, and alternate way of viewing the ochrs:tags function but narrowed to a specific tag.
